
networks:
  default:
  traefik:
    external: true

services:
  nextcloud-db:
    image: mariadb:10.5
    container_name: nextcloud-db
    restart: unless-stopped
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - ./volumes/db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_PASSWORD=${MYSQL_NEXTCLOUD_PASSWORD}
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
    # healthcheck:
    #   test: ["CMD", "mysqladmin", "ping", "--silent"]
    #   timeout: 10s

  nextcloud-redis:
    image: redis
    container_name: nextcloud-redis
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      timeout: 10s

  nextcloud:
    image: nextcloud:${NEXTCLOUD_VERSION}
    container_name: nextcloud
    restart: unless-stopped
    links:
      - nextcloud-db
      - nextcloud-redis
    volumes:
      - ./volumes/data:/var/www/html
    environment:
      - APACHE_DISABLE_REWRITE_IP=1
      - TRUSTED_PROXIES=traefik
      - NEXTCLOUD_TRUSTED_DOMAINS=${NEXTCLOUD_DOMAIN}
      - NEXTCLOUD_ADMIN_USER=${NEXTCLOUD_ADMIN_USERNAME}
      - NEXTCLOUD_ADMIN_PASSWORD=${NEXTCLOUD_ADMIN_PASSWORD}
      - OVERWRITEPROTOCOL=https
      - PHP_UPLOAD_LIMIT=2G

      - MYSQL_HOST=nextcloud-db
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=${MYSQL_NEXTCLOUD_PASSWORD}
      - MYSQL_DATABASE=nextcloud
      - REDIS_HOST=nextcloud-redis

    env_file:
      - ../${ENV_FILE} # load selected environment file
    networks:
      - traefik # add to traefik network
      - default # add to default (stack internal) network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nextcloud.rule=Host(`${NEXTCLOUD_DOMAIN}`)"
      - "traefik.http.routers.nextcloud.entrypoints=websecure"

  nextcloud-cron:
    container_name: nextcloud-cron
    image: nextcloud:${NEXTCLOUD_VERSION}
    restart: unless-stopped
    links:
      - nextcloud-db
    volumes:
      - ./volumes/data:/var/www/html
    entrypoint: /cron.sh
    environment:
      - MYSQL_HOST=nextcloud-db
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=${MYSQL_NEXTCLOUD_PASSWORD}
      - MYSQL_DATABASE=nextcloud
